meta_product_name: "logo@Table"
meta_title: "Un outil unique pour centraliser toutes vos reservations"
meta_description: "Améliorer votre expérience client grâce à une solution centralisée de réservation pour votre restaurant"
meta_image: "@table.png"
